version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "account-init"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fe910p8ktrlv"
s3_prefix = "account-init"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
