version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "balance-validator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ttqinc9njoo9"
s3_prefix = "balance-validator"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
